#!/usr/bin/env bash
# setup-vps-webapp.sh — Stand up the Lumin web app (PWA) static site behind
# nginx + Let's Encrypt.
#
# The web channel (2026-07-18) is the iPhone path: users open
# app.luminapp.org in Safari and Add to Home Screen — no App Store.  The
# lumin-app repo's CI (build-web job) ships build/web into WEB_ROOT on
# every main push; this script provisions the nginx server block + cert
# that serve it.  Mirrors setup-vps-api.sh: idempotent, re-run to refresh
# the nginx config.  Run on the VPS as root.
#
# Usage:
#   sudo bash tools/setup-vps-webapp.sh                 # first-time setup
#   sudo bash tools/setup-vps-webapp.sh --domain app.example.com --email me@example.com
#   sudo bash tools/setup-vps-webapp.sh --no-cert       # HTTP-only (testing)
#
# Args:
#   --domain    DNS name pointing at this VPS (default app.luminapp.org)
#   --email     Email for Let's Encrypt registration / renewal alerts
#   --web-root  Static docroot the CI deploy targets (default /var/www/app.luminapp.org)
#   --no-cert   Skip Let's Encrypt
set -euo pipefail

# ─── Output helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✅  $*${NC}"; }
warn() { echo -e "${YELLOW}⚠️   $*${NC}"; }
err()  { echo -e "${RED}❌  $*${NC}" >&2; }
info() { echo -e "${CYAN}ℹ️   $*${NC}"; }
hdr()  { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════════${NC}"; \
         echo -e "${BOLD}${CYAN}  $*${NC}"; \
         echo -e "${BOLD}${CYAN}══════════════════════════════════════════════${NC}"; }

# ─── Defaults ──────────────────────────────────────────────────────────────────
DOMAIN="${APP_DOMAIN:-app.luminapp.org}"
EMAIL="${APP_LE_EMAIL:-}"
WEB_ROOT="${WEB_ROOT:-/var/www/app.luminapp.org}"
SKIP_CERT=false
NGINX_SITE="lumin-webapp"

# ─── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain)   DOMAIN="$2"; shift 2 ;;
        --email)    EMAIL="$2"; shift 2 ;;
        --web-root) WEB_ROOT="$2"; shift 2 ;;
        --no-cert)  SKIP_CERT=true; shift ;;
        -h|--help)
            sed -n '2,22p' "$0"
            exit 0
            ;;
        *)
            err "Unknown argument: $1"
            exit 1
            ;;
    esac
done

# ─── Pre-flight ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    err "Run as root (sudo bash tools/setup-vps-webapp.sh)"
    exit 1
fi

# ─── PHASE 1 — nginx + certbot install ─────────────────────────────────────────
hdr "PHASE 1 — install nginx + certbot"

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
PKGS="nginx"
if [[ "$SKIP_CERT" == "false" ]]; then
    PKGS="$PKGS certbot python3-certbot-nginx"
fi
apt-get install -y -qq $PKGS >/dev/null
ok "nginx + certbot installed"

systemctl enable nginx --quiet
systemctl start nginx

# ─── PHASE 2 — docroot ─────────────────────────────────────────────────────────
hdr "PHASE 2 — docroot $WEB_ROOT"

mkdir -p "$WEB_ROOT"
chmod 755 "$WEB_ROOT"
# Placeholder page until the first CI deploy lands, so the cert issuance
# and smoke test don't 403 on an empty root.
if [[ ! -f "$WEB_ROOT/index.html" ]]; then
    cat > "$WEB_ROOT/index.html" <<'EOF_PLACEHOLDER'
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Lumin</title>
<style>body{background:#0A0E1A;color:#9aa7b4;font:16px -apple-system,Roboto,sans-serif;
display:flex;align-items:center;justify-content:center;height:100vh;margin:0}</style>
</head><body>Lumin web app — first deploy pending.</body></html>
EOF_PLACEHOLDER
    info "Placeholder index.html written (replaced by the first CI deploy)"
fi

# ─── PHASE 3 — nginx site config ───────────────────────────────────────────────
hdr "PHASE 3 — nginx site for $DOMAIN"

cat > "/etc/nginx/sites-available/$NGINX_SITE" <<EOF_SITE
# Lumin web app (PWA) — generated by tools/setup-vps-webapp.sh
# Don't hand-edit; re-run the script with new flags instead.
#
# Static-only: the app talks to api.luminapp.org for data.  Caching
# policy is the standard Flutter-web split — the bootstrap documents
# (index.html, flutter_bootstrap.js, service workers, manifest) must
# revalidate on every load so a new deploy is picked up immediately,
# while the content-hashed bundle files cache long.
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    root $WEB_ROOT;
    index index.html;

    # ACME challenges (lets-encrypt) need to reach the filesystem.
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Never cache the deploy-entry documents: a stale index.html or
    # service worker pins users to an old build — and web deploys ARE
    # the update mechanism for this channel.
    location ~ ^/(index\\.html|flutter_bootstrap\\.js|flutter_service_worker\\.js|firebase-messaging-sw\\.js|version\\.json|manifest\\.json)\$ {
        add_header Cache-Control "no-cache, must-revalidate" always;
        try_files \$uri =404;
    }

    location / {
        # Flutter's bundle files (main.dart.js parts, canvaskit, assets)
        # are fingerprinted per build via the service-worker hash map, so
        # a moderate cache is safe and saves the VPS re-serving ~2 MB per
        # visit.  No SPA rewrite needed: the app uses hash-free
        # single-document routing.
        add_header Cache-Control "public, max-age=3600" always;
        try_files \$uri \$uri/ =404;
    }

    # Block obvious vuln-scanner probes early (mirrors the API site).
    location ~* \\.(php|asp|aspx|jsp)\$ { return 444; }
    location ~ /\\.(git|env|svn|htaccess) { return 444; }

    access_log /var/log/nginx/lumin-webapp.access.log;
    error_log  /var/log/nginx/lumin-webapp.error.log warn;
}
EOF_SITE

ln -sf "/etc/nginx/sites-available/$NGINX_SITE" "/etc/nginx/sites-enabled/$NGINX_SITE"

if nginx -t 2>&1 | grep -q "successful"; then
    systemctl reload nginx
    ok "nginx reloaded with $NGINX_SITE site"
else
    err "nginx config test failed:"
    nginx -t
    exit 1
fi

# ─── PHASE 4 — Let's Encrypt cert ──────────────────────────────────────────────
hdr "PHASE 4 — Let's Encrypt cert"

if [[ "$SKIP_CERT" == "true" ]]; then
    warn "Skipping cert (--no-cert) — web app will be HTTP-only on $DOMAIN"
elif [[ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]]; then
    # Re-runs rewrite the site file, wiping certbot's injected 443 block;
    # ``certbot install`` re-injects without re-issuing (same pattern as
    # setup-vps-api.sh).
    ok "Cert already exists for $DOMAIN — re-deploying to nginx"
    certbot install -n --cert-name "$DOMAIN" --nginx --redirect 2>&1 | tail -3
    systemctl reload nginx
    ok "443 server block re-injected, nginx reloaded"
else
    if [[ -z "$EMAIL" ]]; then
        warn "No --email given — using --register-unsafely-without-email"
        certbot --nginx -n --agree-tos --redirect --register-unsafely-without-email -d "$DOMAIN"
    else
        certbot --nginx -n --agree-tos --redirect --email "$EMAIL" -d "$DOMAIN"
    fi
    ok "Cert provisioned for $DOMAIN"
fi

# ─── PHASE 5 — smoke test ──────────────────────────────────────────────────────
hdr "PHASE 5 — smoke test"

SCHEME="https"
[[ "$SKIP_CERT" == "true" ]] && SCHEME="http"
CODE=$(curl -s -o /dev/null -w '%{http_code}' "$SCHEME://$DOMAIN/" || true)
if [[ "$CODE" == "200" ]]; then
    ok "$SCHEME://$DOMAIN/ → 200"
else
    warn "$SCHEME://$DOMAIN/ → $CODE (DNS may not point here yet — Cloudflare record needed)"
fi

hdr "DONE"
info "Docroot: $WEB_ROOT (CI deploys here on every lumin-app main push)"
info "Add the Cloudflare DNS A record for $DOMAIN → this VPS if not present."
